# Generated by Django 3.0.3 on 2020-03-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pruduct_keeper', models.CharField(max_length=16, unique=True)),
                ('pruduct_name', models.CharField(max_length=32)),
                ('product_image', models.ImageField(upload_to='image/productimage')),
                ('pruduct_description', models.CharField(max_length=50)),
                ('pruduct_type', models.IntegerField(default=0)),
                ('pruduct_price', models.FloatField()),
                ('prodect_sales', models.IntegerField()),
                ('prodect_date', models.DateField()),
                ('prodect_isdelete', models.BooleanField()),
                ('prodect_discount', models.FloatField()),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pruduct_type_keeper', models.CharField(max_length=16, unique=True)),
                ('pruduct_type_no', models.IntegerField()),
                ('pruduct_type_name', models.CharField(max_length=16, unique=True)),
            ],
            options={
                'db_table': 'productType',
            },
        ),
        migrations.CreateModel(
            name='Retailers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retailer_user_name', models.CharField(max_length=16, unique=True)),
                ('retailer_user_phone', models.CharField(max_length=15, unique=True)),
                ('retailer_name', models.CharField(max_length=16, unique=True)),
                ('retailer_address', models.CharField(max_length=32, unique=True)),
                ('retailer_keeper', models.CharField(max_length=8)),
                ('retailer_capital', models.FloatField()),
            ],
            options={
                'db_table': 'retailer',
            },
        ),
        migrations.CreateModel(
            name='sumAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdate', models.DateField()),
                ('samount', models.FloatField()),
            ],
            options={
                'db_table': 'sumAmount',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=16, unique=True)),
                ('user_password', models.CharField(max_length=256)),
                ('user_phone', models.CharField(max_length=15, unique=True)),
                ('is_certify', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
